---
- name: Primary Proxy Erişilebilirlik Kontrolü
  hosts: ansible_worker
  gather_facts: no
  vars:
    zabbix_url: "{{ zabbix_url }}"
    zabbix_user: "{{ zabbix_user }}"
    zabbix_password: "{{ zabbix_password }}"
    primary_proxy_host: "{{ primary_proxy_host }}"
    dr_proxy_host: "{{ dr_proxy_host }}"
    check_script_path: "/data/projects/_16__disaster_recovery_proxy_automation/check_proxy_status.py"
  tasks:
    - name: Primary Proxy Zabbix adını hostvars'tan al
      set_fact:
        primary_proxy_zabbix_name: "{{ hostvars[primary_proxy_host].zabbix_name }}"
        primary_proxy_ip: "{{ hostvars[primary_proxy_host].ansible_host }}"

    - name: Zabbix API ile primary proxy kontrolü yap (zabbix_name ile)
      ansible.builtin.command: >
        python3 {{ check_script_path }}
        {{ zabbix_url }} {{ zabbix_user }} {{ zabbix_password }} {{ primary_proxy_zabbix_name }}
      register: zabbix_check
      ignore_errors: yes

    - name: Ping ile primary proxy kontrolü yap
      ansible.builtin.command: ping -c 1 {{ primary_proxy_ip }}
      register: ping_result
      ignore_errors: yes

    - name: Sonucu belirle (herhangi biri başarısızsa failure)
      set_fact:
        proxy_check_result: "success"
      when: zabbix_check.rc == 0 and ping_result is defined and ping_result.rc == 0

    - name: Sonucu failure olarak ayarla (herhangi biri başarısızsa)
      set_fact:
        proxy_check_result: "failure"
      when: proxy_check_result is not defined

    - name: Sonucu ekrana yazdır
      debug:
        msg: "Proxy kontrol sonucu: {{ proxy_check_result }}" 